version: '3.8'

services:
  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: genpass-app
    ports:
      - "84:80"
    environment:
      - NODE_ENV=production