version: '3.8'

services:
  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: genpass-app
    ports:
      - "84:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start