version: '3.8'

name: genpass
services:
  app:
    build:
      context: ./frontend
    container_name: genpass-app
    ports:
      - "84:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start